name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
 AWS_REGION: us-west-1
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 DOCKER_HUB_USERNAME: ${{ secrets.USERNAME }} 
 DOCKER_HUB_PASSWORD: ${{ secrets.PASSWD }}

jobs:
 deploy:
  runs-on: windows-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v1

  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ env.DOCKER_HUB_USERNAME }}
      password: ${{ env.DOCKER_HUB_PASSWORD }}

  - name: Build and push Docker image
    run: |
      docker build .
      docker push mohanaprasath/frontend:latest
      
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-region: ${{ env.AWS_REGION }}
      aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

  - name: Configure AWS ECS
    run: |
      aws configure set default.region ${{ env.AWS_REGION }}
      aws configure set ecs.region ${{ env.AWS_REGION }}
  - name: Update ECS service
    run: |
      ecs deploy \
      --service-name lin-NP-USW1-SN\
      --cluster lin-NP-USW1-ECS \
      --mohanaprasath/frontend:latest \
      --timeout 900 \
      --max-healthy-percent 200 \
      --min-healthy-percent 50
